### ISSUE TITLE
[bug] Can't disable global network policies for egress or ingress

### ISSUE THREAD

**Issue by csantanapr** [gitops-bridge-dev/gitops-bridge-helm-charts#15]
If I set `enabled: false`
like this, it stills create the policies
```yaml
networkPolicies:
  enabled: true
  egress:
    deny:
      all:
        enabled: disable
  ingress:
    deny:
      all:
        enabled: disable
```
