### ISSUE TITLE
[feature] network policies should not have namespace in the name

### ISSUE THREAD

**Issue by csantanapr** [gitops-bridge-dev/gitops-bridge-helm-charts#16]
currently deny all creates with the namespace name
```yaml
# Source: team/templates/networkpolicy/ingress/deny-all.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: namespace2-ingress-deny-all
  namespace: namespace2
```
it should be like this
```yaml
# Source: team/templates/networkpolicy/ingress/deny-all.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-deny-all
  namespace: namespace2
```

this looks like a break in backwards compatible would require a major version bump
